DROP DATABASE IF EXISTS bd_card;
CREATE DATABASE IF NOT EXISTS bd_card;
USE bd_card;


CREATE TABLE tb_user(
pseudo VARCHAR (15) NOT NULL,
mdp VARCHAR(100) NOT NULL,
email VARCHAR(50) NOT NULL,
gender VARCHAR(10) NOT NULL,
adresse VARCHAR(80) NOT NULL,
tel INT(10) NOT NULL,
PRIMARY KEY(pseudo)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;



SELECT * FROM tb_user;